version: '3.9'

services:
  grafana:
    image: grafana/grafana
    environment:
      - VIRTUAL_HOST=grafana.yourdomain.tld
      - VIRTUAL_PORT=3000
      - LETSENCRYPT_HOST=grafana.yourdomain.tld
    networks:
      - front
      - back

networks:
  front:
    external:
      name: proxy_front
  back:
    external:
      name: influxdb_back