version: '3.9'

services:
  mongodb:
    image: mongo:latest
    volumes:
      - mongodb-data:/data/db
    env_file:
      - mongodb.env
    networks:
      - back
  mongoexpress:
    image: mongo-express:latest
    environment:
      - VIRUAL_HOST=mongo.yourdomain.tld
      - VIRTUAL_PORT=8081
      - LETSENCRYPT_HOST=mongo.yourdomain.tld
    env_file:
      - mongo-express.env
    networks:
      - back
      - front
volumes:
  mongodb-data:

networks:
  back:
    driver: bridge
  front:
    external:
      name: proxy_front